### PR TITLE
interactive bots: Run the helloworld bot for Gronekmaster.

### PR DESCRIPTION
**Pull request by Gronekmaster**

### CODE REVIEW

**Comment by tommyip** [comment]
Hi @Gronekmaster , you are almost done! You just forgot this:

> Note down any places you got stuck, problems or errors you ran into while doing this setup process. Add your notes as a notes.md file to interactive-bots/helloworld/<username>/ in the zulip/zulip-gci-submissions repository.

Please use amend your commit instead of opening a PR, you can ask on https://chat.zulip.org/#narrow/stream/GCI.20help/ if you are unsure how to do this. Thanks again!

**Comment by Gronekmaster** [comment]
@tommyip but I wasn't stuck - Getting started is okay in my opinion

**Comment by tommyip** [comment]
Awesome! How about anything you like about the whole process?

**Comment by Gronekmaster** [comment]
@tommyip I've added `notes.md` file

**Comment by alenavolk** [comment]
Hi @Gronekmaster! Everything looks great! The only thing you'll need to do before this task gets approved is to squash the second commit into the first one. [This guide](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md#squashing-commits) explains how to do that. After you're done, your pull request must contain one commit with the following commit message: "interactive bots: Run the helloworld bot for Gronekmaster." If you're not sure how to do that or have any questions at all, please feel free to join us at the `#GCI help` stream of the [Zulip Community Chat](https://chat.zulip.org). We'll walk you through every step if necessary :)

**Comment by Gronekmaster** [comment]
I think I've finally fixed it!

**Pull request merged**
