### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by manmita**

### CODE REVIEW

**Comment by roberthoenig** [comment]
Almost looks good @manmita! Your PR should only have two commits, can you squash `Update hello-world.md` into `Create hello-world.md`?

**Comment by manmita** [comment]
Can I create a new pull request, as I was using other laptop there was some issue with the commits

**Comment by manmita** [comment]
I have squashed the required commits, Please kindly check :)

**Comment by jeremyphilemon** [comment]
Good job on squashing the commits @manmita. You've now got the right number of commits, however, the commit messages are not according to those mentioned in the [ task documentation](https://github.com/zulip/zulip-gci/blob/master/tasks/2017/submit-a-pull-request.md). Can you amend the two commit messages to `Add hello-world.md.` and `hello-world.md: Change username to GitHub handle.` respectively?

For instructions on how to change commit messages, read http://zulip.readthedocs.io/en/latest/git/fixing-commits.html#changing-commit-messages

(Don't forget to force push your changes after you're done fixing)

**Comment by manmita** [comment]
I changed the messages, please review

**Comment by shubhamdhama** [comment]
It's fine now, Great work @manmita , hope this PR made you more comfortable in Git.

**Pull request merged**
