### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by Abijith10**

### CODE REVIEW

**Comment by abhijeetkaur** [comment]
@Abijith10 This looks nice! If you want the mentors to review your pull request, you should "Submit" it in the task. (Just informing, if by any chance you forgot to submit and waiting for mentor's feedback)

**Comment by Abijith10** [comment]
@abhijeetkaur I am really glad that you liked it! I have one small issue regarding the "Sign the Dropbox CLA using the link posted by the Dropbox CLA bot." I can't find it anywhere. 

Thanking in advance. :)

**Comment by Balaji2198** [comment]
Awesome @Abijith10. Good work!. The task is updated now. Can you check it again?

**Comment by Abijith10** [comment]
@Balaji2198 Thank so much! :) Yes I have checked it now and it is fixed! :)

**Comment by tommyip** [comment]
Hi @Abijith10. To have this task approved, you need to make the following changes:
* The PR title should be `Submit a Pull Request` (noticed the capital `P` and `R`)
* There should be 2 commits (with the exact wording):
  * 1) `Add hello-world.md.`
  * 2) `hello-world.md: Change username to GitHub handle.`

For the second change, you would need do a interactive rebase on your git branch. If you are not sure about this, feel free to ask on Zulip.

[Cross posted this in the GCI app]

**Comment by lonerz** [comment]
@Abijith10 thanks for submitting the task! Here's a more detailed explanation on what you need to do:

Your commit messages seem to be off. You should delete the first two commits, which aren't necessary.

Afterwards, you should rename your `Create hello-world.md` commit message to be `Add hello-world.md.`

Finally, you should squash your last two commits and rename the commit to be `hello-world.md: Change username to GitHub handle.`

This doc: https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md may be of help.

**Comment by aero31aero** [comment]
Thanks for working on this @Abijith10! There are some things that still need to be done here:

1. The file path should be `/submit-a-pull-request/<username>/hello-world.md` instead of `/<username>/hello-world.md`. It seems like you accidentally created the new directory outside the task's directory.

2. Also, this task requires you to have *precisely* 2 commits. This means that you would have to squash your first three commits into one commit and the last two commits into another.

You might want to read [this tutorial](https://zulip.readthedocs.io/en/latest/git/fixing-commits.html) if you are not familiar with squashing commits.

**Comment by Balaji2198** [comment]
@Abijith10  Created another PR #49  for this.  So closing this one.
Thanks for working on this @Abijith10.

**Pull request merged**
