### PR TITLE
interactive bots: Run the helloworld bot for IksinskiYT

### PR DESCRIPTION
**Pull request by iksinskiyt**

### CODE REVIEW

**Comment by eeshangarg** [comment]
@iksinskiyt: This looks good! However, your commit messages are wrong! There should only be 1 commit in this PR and the commit message should be `interactive bots: Run the helloworld bot for <username>.` as specified in the task instructions. I would recommend squashing your commits into one and changing the commit message while you do so. Here's a hint:

1. Run `git rebase -i HEAD~2`
2. Replace `pick` with `squash` in front of the `Screenshots!` commit. This will squash the second commit into the first one.
3. When you save, it will take you to a screen and tell you to change the commit message, and you can change it to what the task instructions say it should be. :)
4. Lastly, run `git push origin master --force`. And that should do it!

Or, you can follow [this tutorial on squashing commits](https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/) and do the same thing! If you have any questions, feel free to reach out to us on `chat.zulip.org`. Thanks! :)

**Comment by eeshangarg** [comment]
@iksinskiyt: Ah this is super close to perfect! Just one last thing, use `git commit --amend` to amend the commit message to end with a period and the push the changes again. Its a convention within the Zulip project that all commit messages should end with a period! Thanks! :)

**Comment by iksinskiyt** [comment]
Here comes the dot 🦊

**Comment by eeshangarg** [comment]
@iksinskiyt: Awesome! Merged! :)

**Pull request merged**
