### PR TITLE
interactive bots: Run the helloworld bot for Abijith10.

### PR DESCRIPTION
**Pull request by Abijith10**

### CODE REVIEW

**Comment by abhijeetkaur** [comment]
Awesome @Abijith10! Just a few commit message edits:
* Your second commit is empty, you need to remove that. Run `git rebase -i HEAD~2` and remove the second commit line. Read about interactive rebase. Once you have done this,, only then go to the next point.
* Your first commit message is missing a period at the end of the sentence. You should run `git commit --amend` to amend the commit message.
* You should only see 1 commit in your branch. You'll need to do a force push.

If you have any doubts please feel free to have a chat with us. Thanks! :)

**Comment by alenavolk** [comment]
Hey @Abijith10! Could you please fix small typos in you notes?
* a aspiring programmer → an aspiring programmer
* struck → stuck (several times)

Other than that everything is great! And you even mentioned us in your notes, how nice of you :)

**Comment by Abijith10** [comment]
Yeah! All with help from the mentors I can believe myself that I have learner so much in such a short time.

**Comment by Abijith10** [comment]
Learned*

**Comment by alenavolk** [comment]
@Abijith10 Just imagine how much you can learn till the end of the program :)

**Comment by Abijith10** [comment]
Yeah @alenavolk Excited! :D 
By the way, I have changed it.

**Comment by alenavolk** [comment]
Awesome, thanks! Could you also squash these two commits into one? The task description requires  only one commit the with the commit message: "interactive bots: Run the helloworld bot for Abijith10." And the title of the pull request should be the same as the commit message (you can change it right here, on GitHub). I'm sorry I didn't mention that earlier, I just noticed.

**Comment by Abijith10** [comment]
Yeah in the process of it! :)

**Comment by Abijith10** [comment]
@alenavolk  Seems like I messed up something with there and it shows me this now! :/ "This branch cannot be rebased due to conflicts"

**Comment by alenavolk** [comment]
@Abijith10 That's alright, you just need to clean up your commit history a little bit. Can you come to the chat now?

**Pull request merged**
