### PR TITLE
user guides: Review user documentation for Notifications.

### PR DESCRIPTION
**Pull request by ViRu-ThE-ViRuS**
GCI Task (Part 1) -> https://codein.withgoogle.com/dashboard/task-instances/4915071366987776/
GCI Task (Part 2) -> https://codein.withgoogle.com/dashboard/task-instances/4987874753642496/

### CODE REVIEW

**Comment by digi0ps** [comment]
Thanks for the feedback, @ViRu-ThE-ViRuS. Nice work!

**Comment by ViRu-ThE-ViRuS** [comment]
@digi0ps I went ahead and also completed the Part 2. 
Thanks for your support and quick response. :-)

**Comment by digi0ps** [comment]
That's awesome, @ViRu-ThE-ViRuS.
But it would be better if you made a new pull request. Also, try adding some more suggestions or comments!

**Comment by ViRu-ThE-ViRuS** [comment]
I will try out all the operations again to find more suggestions. But I can't create a new pull request unless this one is accepted.

**Comment by digi0ps** [comment]
Alright no problem. 
Part B looks great now! Thanks for the suggestions again.

**Comment by ViRu-ThE-ViRuS** [comment]
@digi0ps should I close the PR, as I am working on a different task which also requires making a pull request... and It wont be accepted with so many commits.

**Comment by digi0ps** [comment]
You can make multiple PRs, there's no limit on that.

**Pull request closed without merging**
