### PR TITLE
interactive bots: Run the helloworld bot for fredfishgames.

### PR DESCRIPTION
**Pull request by fredfishgames**

### CODE REVIEW

**Comment by roberthoenig** [comment]
This looks great @fredfishgames! Can you edit the commit message so it ends with a `.`? Once that's done, I'm approving the task.
(If you need help with editing the commit message, you can check our our [git guide for fixing commits](https://github.com/zulip/zulip-gci/blob/master/docs/fixing-commits.md).

**Comment by fredfishgames** [comment]
done

**Comment by fredfishgames** [comment]
oh did it make a new commit?

**Comment by fredfishgames** [comment]
oh it didn't, that was wierd

**Comment by fredfishgames** [comment]
put a . on the PR title aswell

**Comment by roberthoenig** [comment]
Merged and approved.

**Pull request merged**
