### PR TITLE
Submit a Pull Request

### PR DESCRIPTION
**Pull request by cPhost**
Task 1

### CODE REVIEW

**Comment by trueskawka** [comment]
Hi @cPhost!

Have you claimed and submitted the task in the GCI app? The mentors can review tasks that have been submitted.

Also, could you read the instructions carefully? You should have two commits in this pull request :)

**Comment by eeshangarg** [comment]
@cPhost: This is almost perfect! Just one more thing, if you read the instructions, the commit messages that we specified there have periods at the end but your commit messages don't. I would suggest amending the commit message for both the commits to end with a period. :) This is a convention that everyone follows within the Zulip project! If you have any questions, feel free to post on https://chat.zulip.org/#

Thanks,
Eeshan

**Comment by cPhost** [comment]
@eeshangarg added `.` at the end of commit message.

**Comment by eeshangarg** [comment]
@cPhost: Could you resubmit the task please? I need you to do that before I can approve it!

**Comment by rheaparekh** [comment]
@cPhost Looks good to me! Congratulations on completing your first task! :) @roberthoenig can you merge this?

**Comment by roberthoenig** [comment]
@cPhost looks good to me as well, just one small nit left: The text in the instructions says
```
```
Hello world
I am username. :tada:
```
Your comment capitalizes "World". Once that's fixed, we'll approve the task :) 

We aren't usually this strict regarding typing on other tasks, but for submit-a-pull-request, we have an automatic grader students can use to check if there are any mistakes left in their PRs (see https://github.com/zulip/zulip-gci/blob/master/tasks/2017/submit-a-pull-request.md#submit).

**Comment by cPhost** [comment]
@roberthoenig addressed the nit.

**Comment by roberthoenig** [comment]
@cPhost almost :) You changed it for the second commit; can you change it for the first commit as well?

**Comment by cPhost** [comment]
@roberthoenig both commits fixed.

**Comment by lonerz** [comment]
@cPhost did you submit in the GCI app? Seems like you abandoned the task.

**Comment by cPhost** [comment]
@lonerz i think you guys approved it?

**Comment by lonerz** [comment]
Oh, hm. Looks like they didn't merge your PR.

**Comment by lonerz** [comment]
Merged, thanks @cPhost!

**Pull request merged**
