### PR TITLE
 interactive bots: Run the helloworld bot for sColin16.

### PR DESCRIPTION
**Pull request by sColin16**
I know the commits are littered with previous commits from other projects, but I do not know how to remove them. If all the extra commits are not O.K, please let me know how best to remove them. Thanks in advanced.

### CODE REVIEW

**Comment by eeshangarg** [comment]
@sColin16: Your changes look good but the commit history is a bit messed up, that's okay, we can fix that. Try to [rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages) and remove every commit that you don't need. Usually you can go:

```
git rebase -i HEAD~7
```
and then replace `pick` with `drop` for all of the commits you want to remove and then save and exit and push your changes and that should do it! I still recommend going through this [rebasing tutorial](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages). Good luck! Thanks! :)

**Comment by sColin16** [comment]
Let me know if the changes I made were correct

**Comment by eeshangarg** [comment]
@sColin16: Awesome job! You're very close! The changes look good but its a general convention within Zulip that all commit messages should end in a period. I would recommend running `git commit --amend` and changing the commit message to end in a period and then pushing (add `--force` to the end of the push command if it complains without it). Thanks! :)

**Comment by tommyip** [comment]
Great work! @sColin16

**Pull request merged**
