### PR TITLE
interactive bots: Run the message_info bot for skunkmb.

### PR DESCRIPTION
**Pull request by skunkmb**

### CODE REVIEW

**Comment by roberthoenig** [comment]
@skunkmb this looks great and is very detailed! I'm going to approve your task. Before merging this pull request, can you make sure that you add some line breaks to the super-long lines in the end of `notes.md`? Ideally, they have a maximum length of 80 characters. In other Zulip repositories, maximum line lengths are enforced, so it's good practice :)

**Comment by skunkmb** [comment]
OK, I used the goo.gl link shortener to shorten links in those lines, making them under 80 characters. Does that look good?

**Comment by lonerz** [comment]
Links are fine to be over 80 characters. It's just more of the text.

**Comment by skunkmb** [comment]
Are the line lengths OK now? Can this be merged? Thanks!

**Comment by aero31aero** [comment]
Hey! Amazing work @skunkmb. The notes were very thoughtful and thanks for fixing our documentation.

**Pull request merged**
