### PR TITLE
interactive bots: Run the helloworld bot for caffetaria

### PR DESCRIPTION
**Pull request by Caffetaria**
Hi, 
This is my helloworld bot project.

### CODE REVIEW

**Comment by eeshangarg** [comment]
@Caffetaria: This is almost ready for approval, however, you should only have one commit in this PR, the second one. I would suggest squashing the two commits. You can follow [this tutorial](https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/) to learn how to do that! And feel free to ask on `chat.zulip.org` if you have any questions! Thanks :)

**Comment by Caffetaria** [comment]
@eeshangarg ...thanks for the feedback. Hope I've done it right now.

**Comment by aero31aero** [comment]
Hey. Thanks for working on this! 

Now, instead of 2 commits, there are 5 commits on this PR. You can see the list [here](https://github.com/zulip/zulip-gci-submissions/pull/75/commits). If you notice carefully, you have accidentally added other people's commits onto this PR as well. Its easy to fix and we would love to help you out on https://chat.zulip.org in fixing this PR.

**Comment by synicalsyntax** [comment]
Replaced by #106

**Pull request closed without merging**
