### PR TITLE
user guides: Review user documentation for Account Basics, Part 2.

### PR DESCRIPTION
**Pull request by Privisus**
Link to GCI task: https://codein.withgoogle.com/dashboard/task-instances/6680107236196352/

### CODE REVIEW

**Comment by tommyip** [comment]
Hey @Privisus this is very clear and useful, thanks! Just one thing, can you line wrap the markdown document to 79 characters so it is easier to read in diff.

**Comment by Privisus** [comment]
I used `fold -sw 79 < account-basics-2.md` to line wrap the document. Everything should be line wrapped now.

**Comment by eeshangarg** [comment]
@Privisus: This is great! I have one minor comment. This PR should only have one commit. I would recommend squashing the second commit into the first one. Here's a brief hint on how you can do that:

1. `git rebase -i HEAD~2`
2. Replace `pick` with `squash` in front of the second commit. This will squash the second commit into the previous one.
3. Save and exit.
4. Push your changes, `git push origin task-account-basics-2 --force`. That should do it!

If you have any questions, feel free to reach out to us on `chat.zulip.org`! Once you squash the commits, I'll be happy to merge/approve this right away! Thanks! :)

**Comment by eeshangarg** [comment]
@Privisus: Awesome! Merged and approved! :)

**Pull request merged**
