### PR TITLE
visual art: Create a/an animated reaction

### PR DESCRIPTION
**Pull request by RishiMenon2004**
Thanks for another opportunity to do something I like! GIF creation! I just love pixel animations and I wish that I could earn a living with that! But, I finished my task! I did this because it's Christmas/Winter and wanted to show that Summer is over and will comeback!

### CODE REVIEW

**Comment by sampritipanda** [comment]
Nice work with the animation!

Can you squash all your commits into one commit with the message "visual art: Add a/an <name> animated reaction.", where <name> is the name of your animation e.g. growing heart?

(There is a mistake in the original doc, which doesn't mention the <name> part, we'll fix that).

**Comment by RishiMenon2004** [comment]
Okay.... I don't know what you mean by squash it all into one commit, but I tried to upload all of the files together and that didn't work. So I've only uploaded the gif. Would you tell if a asked a little help by what you mean by "Squash it all into one commit" please?

**Comment by roberthoenig** [comment]
@RishiMenon2004 "squashing commits" means moving all the 7 commits in your PR into a single commit. Additionally, you should include the files you used for creating the gif in this PR.  If you need help with either of these steps, feel free to ask and chat with us on chat.zulip.org.

**Comment by RishiMenon2004** [comment]
git reset --soft HEAD~3 &&
git commit

**Pull request closed without merging**
