### PR TITLE
interactive bots: Run the helloworld bot for nyan-salmon

### PR DESCRIPTION
**Pull request by nyan-salmon**

### CODE REVIEW

**Comment by jajodiaraghav** [comment]
Hi @nyan-salmon 
This looks great. Although, It is necessary that you include a `notes.md` file along with the screenshots. In case you didn't face any issues while working on the task, feel free to mention that in the file.

Add the notes.md file so that we can merge this. Don't forget to do a `git commit --amend` followed by force push to the same branch :)
Thanks

**Comment by nyan-salmon** [comment]
Thank you for reviewing!

I added notes.md!

would you please re-review this request?

**Comment by jajodiaraghav** [comment]
Hi @nyan-salmon 
We should use `git commit --amend --no-edit` when we want to push new changes (like adding notes.md file) to the last commit. 

You have to squash your commits into a single commit. This might help: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits

Feel free to head over to https://chat.zulip.org/#narrow/stream/GCI.20help in case you are stuck.

**Comment by nyan-salmon** [comment]
I had already ran "git commit --amend"  and it looked like a single commit. (at last commit)

However, just to be sure, I ran "git commit --amend --no-edit" again.

If it modify was wrong, please tell me what is wrong...

**Pull request merged**
