### PR TITLE
integrations: Add screenshots and notes for Honeybadger.

### PR DESCRIPTION
**Pull request by MadElf1337**

### CODE REVIEW

**Comment by MadElf1337** [comment]
@roberthoenig Yes, I noticed that, but there seems to be some problem with error reporting in Honeybadger, as I followed the steps to the letter as given in their docs, but it didn't work.
I also contacted them about this matter, and I'm still awaiting their reply.
For commenting, an error should be detected, so without an error, leaving a comment is not possible.

**Comment by roberthoenig** [comment]
I see, so can you add these details to your notes.md? Also, it'd be great if you could still find some fixtures for those cases, even if you cannot generate them. Often, services provide sample fixtures for all their different message cases in their API documentation. If they do, you can copy-paste them into your fixtures PR. If they don't, just mention it in your notes.md :)

**Comment by MadElf1337** [comment]
@roberthoenig No, they have not provided any fixtures

**Comment by MadElf1337** [comment]
But I'll add these errors in notes.md

**Comment by roberthoenig** [comment]
It's still not clear to me for which types of notifications you were able to include a fixture, and for which issues/limitations prevented you from doing so. Maybe create a little table? That would clarify it a lot.

**Comment by roberthoenig** [comment]
Oops, closed accidentally :)

**Comment by MadElf1337** [comment]
Ok, should I do it in other notes section?
@roberthoenig

**Comment by roberthoenig** [comment]
You can, but you can also make a table out of your list of notification types.

**Comment by MadElf1337** [comment]
yes, but should I add it in other notes or after the images?

**Comment by MadElf1337** [comment]
@roberthoenig

**Comment by roberthoenig** [comment]
You should add it in the same notes.md file. 

On another note, github users usually get subscribed to a conversation once they posted a single comment. This means that I get notified about your comments in any case, irrelevant of wether you @-mention me or not :)

**Comment by MadElf1337** [comment]
oh, sorry!
yes I know.
I'm talking about the section in my notes.md called Other Notes
Should I add the table there?

**Comment by roberthoenig** [comment]
You can.

**Comment by MadElf1337** [comment]
okay I'll do that
Can you wait for 5 mins?

**Comment by MadElf1337** [comment]
table
Is this okay?

**Comment by roberthoenig** [comment]
Yes, that looks good.

**Comment by MadElf1337** [comment]
Hey!
I've completed it!
Can you review the task now?
@roberthoenig

**Comment by roberthoenig** [comment]
Merging, thanks @MadElf1337 !

**Pull request merged**
