### PR TITLE
interactive bots: Run the message_info bot for LarsZauberer.

### PR DESCRIPTION
**Pull request by LarsZauberer**
My message_info bot.

### CODE REVIEW

**Comment by shubhamdhama** [comment]
Great @LarsZauberer, everything looks great to me except the test, the problem with your test is that you haven't tested whether the message is sent privately or not, and neither the test of content that the bot replies for your `message`. You can take help of [this](https://github.com/zulip/paython-zulip-api/blob/master/zulip_bots/zulip_bots/bots/followup/test_followup.py#L23).
After making changes you can amend your commit locally and push it to the origin(here is a guide that can help you https://zulip.readthedocs.io/en/latest/git/cheat-sheet.html in doing this[you have to do these steps in a terminal locally]).
Feel free to reach us at https://chat.zulip.org/#narrow/stream/GCI.20help in case of any problem.

**Comment by hrishi3108** [comment]
This is the right [link](https://github.com/zulip/python-zulip-api/blob/master/zulip_bots/zulip_bots/bots/followup/test_followup.py#L13) , the one post has a typo and therefore broken (@shubhamdhama)

**Comment by shubhamdhama** [comment]
Thanks, @hrishi3108, I have updated the link.

**Comment by aero31aero** [comment]
Hey @LarsZauberer this looks good now. However, you have 4 commits in this PR. Can you squash them into one commit as well as rebase this branch with the latest master? If you face difficulty, ask on https://chat.zulip.org on stream GCI Help and mention this comment so that others know what you need help with. :)

**Comment by aero31aero** [comment]
Hey!. It looks like the four commits have now become 7 commits. Did you ask for help on the GCI help stream?

**Comment by LarsZauberer** [comment]
I have asked for help, but it still don't work. Should I make a new pull request?

**Pull request closed without merging**
