### PR TITLE
interactive bots: Run the helloworld bot for imangla

### PR DESCRIPTION
**Pull request by imangla**
I accidentally did not add the text "interactive bots: Run the helloworld bot for imangla" to my commit.

### CODE REVIEW

**Comment by tommyip** [comment]
Hi @imangla, thanks for the pull request! You are nearly there, just a few things:
* You should put all the files in a new folder `interactive-bots/helloworld/imangla`.
* You need to upload a screenshot of "messages sent by you to the bot in the stream "Verona"".
* Note down any places you got stuck, problems or errors you ran into while doing this setup process. Add your notes as a notes.md file to `interactive-bots/helloworld/imangla/`.
* There should be one commit with the title `interactive bots: Run the helloworld bot for imangla.`

**Please do not open a new PR**, instead you should update your commits using git on your terminal or a git GUI tool. Please ask on https://chat.zulip.org/#narrow/stream/GCI.20help if you are unsure how to do this.

**Comment by imangla** [comment]
Done! I'm sorry this is so messy, I'm still trying to find my way around!

**Comment by tommyip** [comment]
@imangla can you join us on https://chat.zulip.org/#narrow/stream/GCI.20help so we can clean this up?

**Comment by tommyip** [comment]
LGTM!

**Pull request merged**
