### PR TITLE
interactive bots: Run the helloworld bot for vedarshshah.

### PR DESCRIPTION
**Pull request by vedarshshah**
[https://codein.withgoogle.com/dashboard/task-instances/6706967340908544/](https://codein.withgoogle.com/dashboard/task-instances/6706967340908544/)

### CODE REVIEW

**Comment by eeshangarg** [comment]
@vedarshshah: This looks good, however there are some unwanted `.DS_Store` files in your PR that shouldn't be there. A good way to avoid this is to run `git status` after you run `git add` to make sure that you didn't add any unneeded system files to your commits. Here's how you can get rid of them:

1. Run `git rebase -i HEAD~1`
2. Replace `pick` with `edit` for the one commit.
3. Delete those files. 
4. Run `git add '*'`. Run `git status` to double-check your changes.
5. Run `git commit --amend`.
6. Run `git rebase --continue`.
7. Run `git push origin master --force`. And that should do it! :)

Thanks!

**Comment by vedarshshah** [comment]
Thanks Eeshan for your inputs. I tried following the directions you gave to remove the .DS_Store files, but somehow my local repo had trouble detecting the commit I had made. So, I created another commit to delete the .DS_Store files.

**Comment by shubhamdhama** [comment]
@vedarshshah , You can reach us at https://chat.zulip.org/#narrow/stream/GCI.20help to get help in fixing this. You don't need to create separate commit to deleting binary files, so you can now simply "squash" your last commit

Run `git rebase -i HEAD~1`
Replace `pick` with `squash` for the one commit.
Now only keep your first commit message.
Run git push origin master --force.

**Comment by vedarshshah** [comment]
This should now be fixed. Thanks **@eeshangarg** and **@shubhamdhama**.

**Comment by eeshangarg** [comment]
@vedarshshah: Happy to merge! Great work! :)

**Pull request merged**
