### PR TITLE
Submit a pull request

### PR DESCRIPTION
**Pull request by russianPotato**

### CODE REVIEW

**Comment by lonerz** [comment]
@russianPotato thanks for submitting! You do need the periods at the end of the commit message. To do this, you should do `git rebase -i HEAD~2`. Change "pick" for both commits to "edit". Save the file and exit. This will start the rebasing process.

Now, do `git commit --amend` to amend the commit message and add a period to the first line (the commit message). Save the file and exit. To continue the rebasing process, do `git rebase --continue`.

Amend the commit message as before. Save the file and exit. And end the rebasing process by `git rebase --continue`.

**Comment by russianPotato** [comment]
I had amended comments, and corrected my mistakes with the periods. I was able to push to GitHub also. Please review my changes.

**Comment by lonerz** [comment]
@russianPotato you should delete your first two original commits (without periods) and get rid of the  "Merge branch" commit. You can follow this doc: http://zulip.readthedocs.io/en/latest/git/troubleshooting.html#undo-a-merge-commit to undo the "Merge commit".

**Comment by russianPotato** [comment]
I think I have messed up my repository, so at this point in time, it will be best to redo the changes.

**Comment by lonerz** [comment]
@russianPotato you can just do `git fetch upstream` and `git reset --hard upstream/master` to reset this branch.

**Pull request closed without merging**
