### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by KrishPandyaR**
hello-world.md: Change username to GitHub handle.

### CODE REVIEW

**Comment by KrishPandyaR** [comment]
Submit a Pull Request

**Comment by jajodiaraghav** [comment]
Hi @KrishPandyaR 
I would request you to go through the instructions at https://github.com/zulip/zulip-gci/blob/master/tasks/2017/submit-a-pull-request.md again.

You have to create your Pull request from `submit-a-pull-request` branch, not `master`. Also, There should be only 2 commits in your PR as mentioned in the link.

Head over to https://chat.zulip.org/#narrow/stream/GCI.20help in case you are stuck.

**Comment by KrishPandyaR** [comment]
Deleted duplicate folder/files in master and created pull request from submit-a-pull-request. Kindly review and share your comment.

**Comment by KrishPandyaR** [comment]
To avoid the wrongly created folder. Going to create new request, so i'm closing this pull request

**Pull request closed without merging**
